// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfMZh-pjGZwzTk6t75ao52WrSBKwKGoKs',
    appId: '1:640195549107:android:893c326c67e3cf3f23ddc6',
    messagingSenderId: '640195549107',
    projectId: 'teka-luxe',
    storageBucket: 'teka-luxe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIz1AIa-1Y8VazeLNWyhEiH7OgkXytDEU',
    appId: '1:640195549107:ios:3feb532bc1ed19c523ddc6',
    messagingSenderId: '640195549107',
    projectId: 'teka-luxe',
    storageBucket: 'teka-luxe.firebasestorage.app',
    androidClientId:
        '640195549107-ihpetiktqo7uagh8s2ddmacd7edf3th8.apps.googleusercontent.com',
    iosClientId:
        '640195549107-fg4g6goj8ag23vdm10m3294eb87ecov3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tekaLuxe',
  );
}
